# De Numpy a TensorFlow
En el taller pasado vimos como crear tensores basicos y como realizar algunas operaciones escenciales con ellos. En este taller veremos algunas funcionalidades mas avanzadas, en especial, este taller esta enfocado en ver como podemos realizar tareas en TensorFlow que normalmente hariamos en Numpy.

In [1]:
import numpy as np
import tensorflow as tf

sess = tf.Session()

### Arrays
En Numpy utilizamos arreglos multidimensionales para realizar toda clase tareas. Creemos algunos arreglos en Numpy como ejemplo y veamos como podemos operar con arreglos de diferentes dimensiones de acuerdo con las reglas del algebra lineal 

In [16]:
# matriz: dimension (3, 4)
a = np.random.randn(3, 4)

# vector: dimension (3)
b = np.random.rayleigh(3.3, size=(3,))

# vector: dimension (4)
c = np.random.uniform(0.0, 1.0, size=(4,))

# escalar: dimension ()
d = 2.0

# calculo de dimensiones: 
# (3) . (3, 4) + () * (4) == (4) + (4) == (4)
f = np.dot(b, a) + d * c

print("Forma: {}".format(f.shape))
print("Valor: {}".format(f))

Forma: (4,)
Valor: [-0.16623515  9.62417575  2.33475716 -7.06859477]


En este ejemplo realizamos operacion estandar, lo importante a tener en cuenta aqui es que realizamos operaciones de forma exitosa con objetos con diferentes formas / shapes. Tener en cuenta la forma de los arreglos es muy importante porque si nos imponen restricciones en la manera como podemos realizar las operaciones. Por ejemplo, anteriormente utilizamos la funcion `dot` (producto punto) para multiplicar un vector de dimension `(3)` con una matriz de dimension `(3,4)`, sin embargo, veamos que si invertimos el orden de la variables vamos a obtener un error: 

In [21]:
try:
    np.dot(a, b)

    
except Exception as e:
    print("Error: {}".format(e))

Error: shapes (3,4) and (3,) not aligned: 4 (dim 1) != 3 (dim 0)


Esta discusion las dimensiones y el orden de las operaciones es muy importante para utilizar Tensores multidimensiones.

### Tensores
El el taller anterior utilizamos unicamente escalares, sin embargo, al igual que los arreglos de numpy, los tensores de tensorflow puede tener varias dimensiones y ejecutar operaciones de algebra lineal. Recreemos el ejemplo anterior en TensorFlow

In [35]:
# matriz: dimension (3, 4)
a = tf.random_normal((3, 4))

# vector: dimension (3)
b = tf.random_gamma((1, 3), 3.3)

# vector: dimension (4)
c = tf.random_uniform((1, 4), 0.0, 1.0)

# escalar: dimension ()
d = 2.0

# calculo de dimensiones: 
# (3) . (3, 4) + () * (4) == (4) + (4) == (4)
f = tf.matmul(b, a) + d * c

print("Forma: {}".format(f.shape))
print("Objeto: {}".format(f))
print("Valor: {}".format(sess.run(f))[0])

Forma: (1, 4)
Objeto: Tensor("add_5:0", shape=(1, 4), dtype=float32)
V


Con la pequeña excepcion de que TensorFlow nos obliga a convertir los tensores `b` y `c` en una matrices de rango `1`, las operaciones de ambos programas son equivalentes. Asi mismo, si invertirmos el orden de las operaciones tambien obtenemos un error

In [31]:
try:
    np.dot(a, b)

    
except Exception as e:
    print("Error: {}".format(e))

Error: Dimensions must be equal, but are 4 and 3 for 'mul_3' (op: 'Mul') with input shapes: [3,4], [1,3].


##### Formas Dinamicas
Ahora bien, algo que podemos hacer con tensores de tensorflow y no podemos hacer con los arreglos de numpy es tener dimensiones variables / indefinidas. Veamos un ejemplo de esto:

In [18]:
# Creemos un tensor placeholder con la primera dimension variable.
# Para crear dimensiones variables utilizamos 'None' en vez de un entero.
x = tf.placeholder(tf.float32, shape=(None, 2), name='x')

# Tensor aleatorio de dimensiones (2, 5)
w = tf.random_normal((2, 5), name='y')

# Producto punto: x . w
# Debido a la reglas de algebra lineal las dimensiones deben ser:
# (?, 2) . (2, 5) == (?, 5)
y = tf.matmul(x, w, name='y')

# Verfifiquemos que la forma/shape si sea: (?, 5)
print(y)
print("")

# Ejecutemos el tensor y visualicemos el resultado.
print(sess.run(y, feed_dict={
    x: np.random.uniform(-1.0, 1.0, size=(4, 2))
}))

Tensor("y_23:0", shape=(?, 5), dtype=float32)

[[-0.09032293  0.24830988  0.21080302  0.88187146  0.08386514]
 [-0.11958653 -0.15867841 -0.07177992 -0.13025115 -0.44506443]
 [-0.4513019  -0.36950359 -0.10580767  0.11904678 -1.41797817]
 [ 0.37724578  0.24509799  0.04253905 -0.26930976  1.11254048]]


### Funciones

### Aplicaciones

### Tareas